[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --strict-markers --basetemp=../pytest-work/tmp
cache_dir = ../pytest-work/cache
pythonpath = . ../data-pipeline ../data-persistence ../toolset
markers =
    asyncio: async tests
    unit: unit tests
    integration: integration tests
    no_storage: test does not use chat history or persistence
